export const themes: Record<string, Record<string, string>> = {
  default: {
    '--color-dark': '#2b2d42',
    '--color-dark-hover': '#13131b',
    '--color-alt': '#8d99ae',
    '--color-light': '#edf2f4',
    '--color-light-hover': '#e0e2e2',
    '--color-accent': '#ef233c',
    '--color-accent-hover': '#d90429',
  },
  ukraine: {
    '--color-dark': '#0057b7',
    '--color-dark-hover': '#004080',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffd700',
    '--color-light-hover': '#ffcc00',
    '--color-accent': '#0057b7',
    '--color-accent-hover': '#004080',
  },
  france: {
    '--color-dark': '#002395',
    '--color-dark-hover': '#001a70',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#ed2939',
    '--color-accent-hover': '#c41f2a',
  },
  emirates: {
    '--color-dark': '#000000',
    '--color-dark-hover': '#222222',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#00732f',
    '--color-accent-hover': '#005f25',
  },
  andorra: {
    '--color-dark': '#0046ae',
    '--color-dark-hover': '#003580',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffcd00',
    '--color-light-hover': '#e6b800',
    '--color-accent': '#d0102a',
    '--color-accent-hover': '#a50c20',
  },
  austria: {
    '--color-dark': '#ed2939',
    '--color-dark-hover': '#c41f2a',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#ed2939',
    '--color-accent-hover': '#c41f2a',
  },
  china: {
    '--color-dark': '#b20000',
    '--color-dark-hover': '#800000',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffeb00',
    '--color-light-hover': '#e6d400',
    '--color-accent': 'red',
    '--color-accent-hover': '#b20000',
  },
  czechia: {
    '--color-dark': '#11457e',
    '--color-dark-hover': '#0d3460',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#d7141a',
    '--color-accent-hover': '#a50f14',
  },
  denmark: {
    '--color-dark': '#c60c30',
    '--color-dark-hover': '#9f0a25',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#c60c30',
    '--color-accent-hover': '#9f0a25',
  },
  egypt: {
    '--color-dark': '#000000',
    '--color-dark-hover': '#222222',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#ce1126',
    '--color-accent-hover': '#a50c1e',
  },
  spain: {
    '--color-dark': '#aa151b',
    '--color-dark-hover': '#7f1014',
    '--color-alt': '#d9d9d9',
    '--color-light': '#f1bf00',
    '--color-light-hover': '#d9aa00',
    '--color-accent': '#aa151b',
    '--color-accent-hover': '#7f1014',
  },
  finland: {
    '--color-dark': '#002f6c',
    '--color-dark-hover': '#00204d',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#002f6c',
    '--color-accent-hover': '#00204d',
  },
  greece: {
    '--color-dark': '#080076',
    '--color-dark-hover': '#0c5fb0',
    '--color-alt': '#d9d9d9',
    '--color-light': 'white',
    '--color-light-hover': 'white',
    '--color-accent': '#080076',
    '--color-accent-hover': '#080076',
  },
  sri_lanka: {
    '--color-dark': '#8d153a',
    '--color-dark-hover': '#6c102d',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffb700',
    '--color-light-hover': '#e6a500',
    '--color-accent': '#006b3f',
    '--color-accent-hover': '#00532f',
  },
  monaco: {
    '--color-dark': '#ce1126',
    '--color-dark-hover': '#a50c1e',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#ce1126',
    '--color-accent-hover': '#a50c1e',
  },
  sweden: {
    '--color-dark': '#006aa7',
    '--color-dark-hover': '#004d7d',
    '--color-alt': '#d9d9d9',
    '--color-light': '#fecc00',
    '--color-light-hover': '#e6b800',
    '--color-accent': '#006aa7',
    '--color-accent-hover': '#004d7d',
  },
  turkey: {
    '--color-dark': '#e30a17',
    '--color-dark-hover': '#b20812',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#e30a17',
    '--color-accent-hover': '#b20812',
  },
  cyprus: {
    '--color-dark': '#d36b00',
    '--color-dark-hover': '#a85300',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#228b22',
    '--color-accent-hover': '#176617',
  },
  vietnam: {
    '--color-dark': '#da251d',
    '--color-dark-hover': '#a91c16',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ff0',
    '--color-light-hover': '#e6e600',
    '--color-accent': '#da251d',
    '--color-accent-hover': '#a91c16',
  },
  norway: {
    '--color-dark': '#ba0c2f',
    '--color-dark-hover': '#8f0924',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#00205b',
    '--color-accent-hover': '#001742',
  },
}
