export const themes: Record<string, Record<string, string>> = {
  default: {
    '--color-dark': '#1A1A1A',
    '--color-dark-hover': '#262626',
    '--color-alt': '#4D4D4D',
    '--color-light': '#edf2f4',
    '--color-light-hover': '#e0e2e2',
    '--color-accent': '#ef233c',
    '--color-accent-hover': '#d90429',
  },
  france: {
    '--color-dark': '#001f4d',
    '--color-dark-hover': '#003580',
    '--color-alt': '#cdd9e8',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f4ff',
    '--color-accent': '#d72631',
    '--color-accent-hover': '#a31823',
  },
  emirates: {
    '--color-dark': '#121212',
    '--color-dark-hover': '#333333',
    '--color-alt': '#ccc9c9',
    '--color-light': '#f8f8f8',
    '--color-light-hover': '#e9e9e9',
    '--color-accent': '#007a2f',
    '--color-accent-hover': '#005c22',
  },
  andorra: {
    '--color-dark': '#00317e',
    '--color-dark-hover': '#0047b3',
    '--color-alt': '#d0d5db',
    '--color-light': '#ffcb05',
    '--color-light-hover': '#ffd633',
    '--color-accent': '#d8112f',
    '--color-accent-hover': '#a50d21',
  },
  china: {
    '--color-dark': '#8c0c12',
    '--color-dark-hover': '#b5282f',
    '--color-alt': '#e0c600',
    '--color-light': '#fff44f',
    '--color-light-hover': '#fff78c',
    '--color-accent': '#cc0000',
    '--color-accent-hover': '#990000',
  },
  czechia: {
    '--color-dark': '#0d3b66',
    '--color-dark-hover': '#154c8a',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f5f5f5',
    '--color-accent': '#d71920',
    '--color-accent-hover': '#a31117',
  },
  egypt: {
    '--color-dark': '#1c1c1c',
    '--color-dark-hover': '#363636',
    '--color-alt': '#c9c9c9',
    '--color-light': '#f9f9f9',
    '--color-light-hover': '#eaeaea',
    '--color-accent': '#d71921',
    '--color-accent-hover': '#9d1215',
  },
  spain: {
    '--color-dark': '#a91d22',
    '--color-dark-hover': '#c92e34',
    '--color-alt': '#d9d9d9',
    '--color-light': '#f7ca18',
    '--color-light-hover': '#ffd633',
    '--color-accent': '#aa151b',
    '--color-accent-hover': '#7f1014',
  },
  finland: {
    '--color-dark': '#002f6c',
    '--color-dark-hover': '#004080',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f3f6fa',
    '--color-accent': '#00509e',
    '--color-accent-hover': '#003366',
  },
  greece: {
    '--color-dark': '#001e5b',
    '--color-dark-hover': '#0a3b90',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f4ff',
    '--color-accent': '#0050a4',
    '--color-accent-hover': '#003f87',
  },
  sri_lanka: {
    '--color-dark': '#7a1d2f',
    '--color-dark-hover': '#991f36',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffbf00',
    '--color-light-hover': '#ffd24d',
    '--color-accent': '#006b3f',
    '--color-accent-hover': '#004f2c',
  },
  cyprus: {
    '--color-dark': '#a76e00',
    '--color-dark-hover': '#c08c00',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#228b22',
    '--color-accent-hover': '#176617',
  },
  vietnam: {
    '--color-dark': '#8b1a15',
    '--color-dark-hover': '#b2241c',
    '--color-alt': '#d1b200',
    '--color-light': '#ffe733',
    '--color-light-hover': '#ffef66',
    '--color-accent': '#d6281d',
    '--color-accent-hover': '#9e1f16',
  },
  norway: {
    '--color-dark': '#8c0e2f',
    '--color-dark-hover': '#b51a40',
    '--color-alt': '#d9d9d9',
    '--color-light': '#ffffff',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#00205b',
    '--color-accent-hover': '#001742',
  },
  austria: {
    '--color-dark': '#a61c28',
    '--color-dark-hover': '#c62534',
    '--color-alt': '#d6d6d6',
    '--color-light': '#fdfdfd',
    '--color-light-hover': '#f4f4f4',
    '--color-accent': '#e53935',
    '--color-accent-hover': '#8b1c1b',
  },
  denmark: {
    '--color-dark': '#a4161a',
    '--color-dark-hover': '#c62828',
    '--color-alt': '#e0e0e0',
    '--color-light': '#fdfdfd',
    '--color-light-hover': '#f7f7f7',
    '--color-accent': '#d32f2f',
    '--color-accent-hover': '#7a1414',
  },
  monaco: {
    '--color-dark': '#a30a1f',
    '--color-dark-hover': '#c21a2e',
    '--color-alt': '#dadada',
    '--color-light': '#fefefe',
    '--color-light-hover': '#f4f4f4',
    '--color-accent': '#e53935',
    '--color-accent-hover': '#8b1c1b',
  },
  turkey: {
    '--color-dark': '#a81b23',
    '--color-dark-hover': '#c72c34',
    '--color-alt': '#d9d9d9',
    '--color-light': '#f9f9f9',
    '--color-light-hover': '#f0f0f0',
    '--color-accent': '#e53935',
    '--color-accent-hover': '#8b1c1b',
  },
  ukraine: {
    '--color-dark': '#003478',
    '--color-dark-hover': '#1a4d9c',
    '--color-alt': '#c4d6eb',
    '--color-light': '#ffd700',
    '--color-light-hover': '#ffe04d',
    '--color-accent': '#0073e6',
    '--color-accent-hover': '#004d99',
  },
  sweden: {
    '--color-dark': '#004b73',
    '--color-dark-hover': '#006399',
    '--color-alt': '#e0e0e0',
    '--color-light': '#fecc00',
    '--color-light-hover': '#ffd633',
    '--color-accent': '#0088cc',
    '--color-accent-hover': '#005b80',
  },
}
